<?php
/**
 * CallsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Ubity API
 *
 * The Ubity API allows you to initiate calls, send text messages (SMS), retrieve call recordings, get a user's phone presence status, and a whole lot more.
 *
 * OpenAPI spec version: 1.0
 * Contact: dev@ubity.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.14
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use Swagger\Client\Configuration;
use Swagger\Client\ApiException;
use Swagger\Client\ObjectSerializer;

/**
 * CallsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class CallsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for callAnswerPost
     *
     * Answering a call.
     *
     */
    public function testCallAnswerPost()
    {
    }

    /**
     * Test case for callHangupPost
     *
     * Hangup a call.
     *
     */
    public function testCallHangupPost()
    {
    }

    /**
     * Test case for callPost
     *
     * Initiate an outgoing call on behalf of a user..
     *
     */
    public function testCallPost()
    {
    }

    /**
     * Test case for callSendToVoicemailPost
     *
     * Send a call to voicemail (while ringing).
     *
     */
    public function testCallSendToVoicemailPost()
    {
    }

    /**
     * Test case for callsPost
     *
     * List running calls.
     *
     */
    public function testCallsPost()
    {
    }
}
