<?php
/**
 * RecordingsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Ubity API
 *
 * *** DISCLAMER *** The SDK is not support by Ubity. The Ubity API allows you to initiate calls, send text messages (SMS), retrieve call recordings, get a user's phone presence status, and a whole lot more!
 *
 * OpenAPI spec version: 1.0
 * Contact: dev@ubity.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.14
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use Swagger\Client\Configuration;
use Swagger\Client\ApiException;
use Swagger\Client\ObjectSerializer;

/**
 * RecordingsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class RecordingsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for recordingPost
     *
     * Get a specific call recording from and ID.
     *
     */
    public function testRecordingPost()
    {
    }

    /**
     * Test case for recordingsGet
     *
     * Get recordings list.
     *
     */
    public function testRecordingsGet()
    {
    }

    /**
     * Test case for recordingsYearGet
     *
     * Get recordings list for specific year.
     *
     */
    public function testRecordingsYearGet()
    {
    }

    /**
     * Test case for recordingsYearMonthDayDirectionGet
     *
     * Get recordings list for specific for a day (with mp3).
     *
     */
    public function testRecordingsYearMonthDayDirectionGet()
    {
    }

    /**
     * Test case for recordingsYearMonthGet
     *
     * Get recordings list for a specific month.
     *
     */
    public function testRecordingsYearMonthGet()
    {
    }
}
